version: '3'
services:
  app:
    build: ./docker/python
    volumes:
      - ./server:/var/www/html
    tty: true
  db:
    image: mariadb:latest

    volumes:
      -  ./dbdata:/var/lib/mysql
    ports:
        - "3307:3306"
    expose:
        - "3307"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "hoge"
volumes:
  dbdata: